# Generated by Django 5.1.4 on 2024-12-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
