# Generated by Django 5.1.4 on 2024-12-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_patientprofile_phone_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='date_of_birth',
        ),
    ]
