# Generated by Django 5.1.4 on 2024-12-22 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('appointment_confirmed', 'Appointment Confirmed'), ('appointment_canceled', 'Appointment Canceled'), ('prescription_uploaded', 'Prescription Uploaded'), ('appointment_created', 'Appointment Created'), ('appointment_rescheduled', 'Appointment Rescheduled')], max_length=50),
        ),
    ]
