# Generated by Django 5.1.4 on 2024-12-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_notification_sent_at_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
